Implement crash alert
monash-human-power/MHP_DAS pull request #110
Opened 2022-12-07 00:48 UTC by jmark-9

## Description

Implements the crash alert system that allows anyone subscribed to receive an alert via their device when the bike crashes.

Adds code that listens for messages from the crash detection and upon receiving a `true`, sends an alert via [this Slack channel](https://monashhumanpower.slack.com/archives/C041XHE6MEJ) in the MHP Slack workspace. This can be extended for more APIs by adding children of the `MessageSender` class and implementing the `send_message()` method with the APIs respective calls.

## Screenshots

Message in the Slack channel when a crash is detected:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/90585684/206054591-0d125b64-fd30-45f8-87f1-ceefce578ccb.png">

## Steps to Test

1. Create/activate your poetry environment using python 3.7. (i.e. `poetry env use 3.7`)
2. Spawn into the environment using `poetry shell`
3. Install the dependencies with `poetry install`
4. Run the main program using `python main_crash_alert.py`

The program should start listening to the MQTT channel:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/90585684/206058743-c06af2fb-fd12-43e1-bea9-fced03ff5e21.png">

5. In another window, publish to the MQTT channel:
```
# to send a false
mosquitto_pub -t "/v3/wireless_module/3/crash_detection" -m '{"value": false}'

# to send a true
mosquitto_pub -t "/v3/wireless_module/3/crash_detection" -m '{"value": true}'
```
When a `true` is sent, a message should be sent in the Slack channel if it has been 10 seconds since the last `true` was received. When a `false` is received, no message should be sent.

2022-12-07 07:35 UTC, jmark-9 commented
Note: you will also need to create a `.env` file in the layout of the example one. The Slack API URL can be found by going to the [Slack API site](https://api.slack.com/) and copying the webhook URL under Your Apps>MHP Crash Alert>Features>Incoming Webhooks

2022-12-07 07:46 UTC, AroshHeenkenda requested changes
It would be good to see a `README` file in the folder, this will save you some hassle later and will give anyone testing some more verbose instructions. I also had an error when running `poetry install`, all the dependencies were installed but once they were installed I received a `Value Error`, could just be a problem on my device but it's worth investigating the lock file.

2022-12-11 05:26 UTC, kdav108 reviewed
Didn't get a chance to run it yet, just went through the code. The OOP framework being used is great! Just have a few small suggestions...

Will try test run it soon.

2022-12-11 05:26 UTC, kdav108 commented on crash_alert/crash_alert.py
> +    def __init__(self, t, slack_webhook):
```suggestion
    def __init__(self, min_time_interval, slack_webhook):
```
Feel free to change it to something else, but would be nice to have something more descriptive than `t`

2022-12-11 05:26 UTC, kdav108 commented on crash_alert/main_crash_alert.py
> +from paho.mqtt import client as mqtt #import the client
```suggestion
from paho.mqtt import client as mqtt
```

2022-12-11 05:26 UTC, kdav108 commented on crash_alert/crash_alert.py
> +        """
Missing docs, here and in `__init__()`

2022-12-11 05:26 UTC, kdav108 commented on crash_alert/main_crash_alert.py
> +            # self.true_count = 0
```suggestion
            return_msg = self.crash_alert.alert()
            logging.debug(return_msg) 
```
Unless really needed, we can remove the commented out code

2022-12-11 05:26 UTC, kdav108 commented on crash_alert/main_crash_alert.py
> +    host = ARGS.host #os.getenv("MQTT_HOST")
Do we use `MQTT_HOST` for env variable as a fallback?

2023-01-09 00:45 UTC, AroshHeenkenda commented on crash_alert/README.md
> +
Add some instructions on setting up the `.env` file, something that tells them where to get the _Slack Webhook from_. Otherwise, the README is fine.

2023-01-09 00:51 UTC, AroshHeenkenda commented
There were some redundant comments scattered in the code, remove any you deem unnecessary.

2023-01-16 01:54 UTC, AroshHeenkenda requested changes
Just this small change, and it should be good to merge.

2023-01-16 01:54 UTC, AroshHeenkenda commented on crash_alert/message_senders/sns_message_sender.py
> +        # assign topic
Redundant comment.

2023-01-17 22:47 UTC, AroshHeenkenda approved these changes
The code looks good and was running fine when connected to the primary display broker.

2023-01-18 13:07 UTC, merged