Zsunnyz/crash detection
monash-human-power/MHP_DAS pull request #115
Opened 2023-01-28 09:35 UTC by samzhang5469

## MPU Sensor
The MPU6050 is used to measure and calculate the state of the bike. Then the wireless module publishes the information to the MQTT broker under the /v3/wireless_module/3/mpu_data topic for acceleration, rotation and gyroscopic data, and /v3/wireless_module/3/crashed_state for crashed state.

## Setup
1. Follow the Getting Started instructions [here](https://github.com/monash-human-power/data-acquisition-system/tree/master/wireless_modules) 
2. Once you have created a local version of the config.py file you can navigate to the ```back_module``` folder.
3. Execute the upload script with 
```bash
# change this to the serial port of the ESP32
./upload.sh --port /dev/ttyUSB0
```
``` bash
# if this is taking a while in your shell, switch shells or alternatively manually upload these files
(
    "main.py" 
    "../config.py" 
    "../wireless_module.py"
    "../boot.py"
    "../mqtt_client.py"
    "../battery_reader.py"
    "../sensors/sensor_base.py"
    "../sensors/co2_sensor.py"
    "../sensors/dht_sensor.py"
    "../sensors/gps_sensor.py"
    "../sensors/mpu_sensor.py"
    "../sensors/reed_sensor.py"
    "../status_led.py"
    "../libraries/abc.py"
    "../libraries/MQ135/mq135.py"
    "../libraries/micropyGPS/micropyGPS.py"
    "../libraries/MPU6050-ESP8266-MicroPython/mpu6050.py"
) 
# using 
ampy -p /dev/ttyUSB0 -b 115200 put <FILE>
```
4. Verify that the file system is uploaded correctly using
```bash
# change /dev/ttyUSB0 to the serial port of the ESP32
ampy -p /dev/ttyUSB0 ls
```
5. Install and setup [Mosquitto](https://mosquitto.org/download/) and make sure its running

## Steps to Test

1. Switch on the primary display
3. Create a mobile hotspot with the previously used ESSID and password
5. Verify that the wireless module, primary display and subscribed devices are all connected to the hotspot
7. Interact with the wireless module through your computer (see [this](https://github.com/monash-human-power/data-acquisition-system/tree/master/wireless_modules/middle_module#steps-to-test))

## Current Tuning Method
It is a good idea to calibrate the sensors on before using it. Notably aim to calibrate the sensor if: the back wireless module is accidently dropped, or: after real crash has been detected.
In the current implementation of the accelerometer, you will need to manually calibrate the sensor if the readings have drifted. Parameters are stored as class attributes of the ```MpuSensor``` within ```mpu_sensor.py```. These tunable values include:
| Parameter| Description |
| --- | ----------- |
| ```xyz_calib_offset``` | Is used to ensure axis readings are zero while perpendicular to the direction of gravity. To tune this parameter. </br>1. Modify the mpu_sensor.py file by adding ```print(accel_values) ``` in line 80 </br>2. Lay the accelerometer with z-axis facing up, and ensure that the accelerometer in on a level surface with a leveler and that there is as little vibration as possible </br>3. Test the device and read the values of x and z. </br> 4. Pick values ```a,b``` for the other two axis x,y such that ```x+a≈0``` and ```y+b≈0```  <br> 5. Verify these values by reorienting the accelerometer with other axis facing directly up. </br> 5. Update the class attribute and reflash the wireless module again before moving on to the next parameter |
| ```xyz_calib_factor``` | This determines how sensitive the accelerometer is. Once xyz_calib_offset it tuning sufficiently, </br>1. Place the accelerometer on a level surface with z axis facing up, find the value of ```a``` such that ```z*a≈1``` </br> 2. Repeat this by reorienting the accelerometer with the calibration axis facing up and solving for ```a``` once again for all other axis readings </br>3. Update the parameter and reflash the wireless module|
| ```gyro_calib_offset``` | This parameter helps to offset the initial error in the gyroscope. Once xyz_calib_factor is complete </br> 1. Place MPU on a flat surface with as little vibration as possible, modify the ```mpu_sensor.py``` code to include ```print(gyro_values)``` instead on ```line 80```  and reflash the wireless module</br> 2. Pick values for ```gyro_calib_offset``` such that the printed values are as close to 0 as possible while at rest </br>3. Reflash the wireless module with the new values.</br> A method will be added to calibrate this automatically soon.|
| complemenatary ratio | The complementary ratio is not store as a class attribute. The tuning is left to the judgement of the user. See [notion](https://www.notion.so/monashhumanpower/Wireless-module-crash-detection-5295c2b1b84e44f980fb0b6abb87bd92) for approach. The actual values are the hardcoded values found in ```line 74``` and ```line 75``` in ```mpu_sensor.py``` |

Currently there is no way to tune gyroscope scaling without the use of specialized testing equipment.

2023-01-28 12:32 UTC, jgOhYeah requested changes
I haven't tested it, but looks good overall.
A couple of things that may need to be addressed or discussed:
- Importing the mpu6500 library as a submodule to keep the version control / lineage of the library in tact. Does the previous mpu6050 library need to be removed from the submodules list in that case?
- A couple of files that appear to be works in progress and can be removed?
- Did the line endings do something weird to edit what seems like every file? Is this something that needs to be cleaned up (Windows vs Linux settings on the git client)?

2023-01-28 12:32 UTC, jgOhYeah commented on wireless_modules/sensors/mpu6500.py
> +# Copyright (c) 2018-2020 Mika Tuupola
Should this file (mpu6500.py) be included as a submodule seeing as it is from another git repository? (not sure how it affects licensing if included here).
https://github.com/tuupola/micropython-mpu9250

2023-01-28 12:32 UTC, jgOhYeah commented on wireless_modules/sensors/mpu_sensor_6500.py
> +from machine import I2C
Is this file needed? It looks to me like it is a backup / work in progress that doesn't seem to be used, but I could be wrong. (mpu_sensor.py is the one that the back wireless module imports).

2023-01-29 11:46 UTC, jgOhYeah requested changes
Getting closer - good work.
Unfortunately it looks like there was a merge that failed at one point and added various bits of text for manual merging, which will break things at some point. These seem to have been added in commit  8a423ab.
For the more minor things that aren't necessarily specific to this PR / affect the functionality:
- A few questions about which config and example config files should be commited or removed.
- Naming of variables that suggest 1 second is 5 times faster than I thought it was :).

2023-01-29 11:46 UTC, jgOhYeah commented on DAS/das/V3_fake_module.py
> +<<<<<<< HEAD
Is this in here on purpose or is it a remnant from a failed merge at some point?

2023-01-29 11:46 UTC, jgOhYeah commented on DAS/das/V3_fake_module.py
> +=======
Also potentially from a failed merge.

2023-01-29 11:46 UTC, jgOhYeah commented on DAS/poetry.lock
> +<<<<<<< HEAD
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on DAS/poetry.lock
> +=======
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on DAS/poetry.lock
> +>>>>>>> ab2fd7f99f13543d1c56b4afcd45ccf5b4b92e56
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on DAS/pyproject.toml
> +<<<<<<< HEAD
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on DAS/pyproject.toml
> +=======
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on DAS/pyproject.toml
> +>>>>>>> ab2fd7f99f13543d1c56b4afcd45ccf5b4b92e56
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on utils/poetry.lock
> +<<<<<<< HEAD
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on utils/poetry.lock
> +=======
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on utils/poetry.lock
> +>>>>>>> ab2fd7f99f13543d1c56b4afcd45ccf5b4b92e56
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on utils/pyproject.toml
> +<<<<<<< HEAD
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on utils/pyproject.toml
> +=======
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on utils/pyproject.toml
> +>>>>>>> ab2fd7f99f13543d1c56b4afcd45ccf5b4b92e56
Part of a failed merge?

2023-01-29 11:46 UTC, jgOhYeah commented on wireless_modules/config.example.py
> -ESSID = "<WIFI NETWORK NAME HERE>"
Is this file meant to be deleted? It looks like it is meant to be kept as a reference to me (might have been renamed to make the actual config file at one point, which git may interpret as removing this one).

2023-01-29 11:46 UTC, jgOhYeah commented on wireless_modules/wireless_module.py
> +        secs_to_ms = 200
Should `secs_to_ms` be renamed to something like `time_scalar`... as 200ms isn't really 1 second (being a bit pedantic :) )?

2023-01-29 11:46 UTC, jgOhYeah commented on wireless_modules_py/wind_module/config.py
> +MQTT_BROKER = "localhost"
Does this need to be turned into the `config.example.py` format that then gets copied to a gitignored `config.py` to make it a bit harder to accidently commit passwords? This is more of a question for the wind sensor project, but putting it here while I remember.

2023-01-31 10:15 UTC, AroshHeenkenda approved these changes
None of these changes should break anything, tested it out myself and works fine. PR approved Sam Zhang.

2023-01-31 10:39 UTC, jgOhYeah approved these changes
Looks good to me

2023-01-31 11:22 UTC, merged