Remove codacy badge from readme
monash-human-power/MHP_DAS pull request #41
Opened 2020-02-21 04:16 UTC by khanguslee

## Description

- Removes the codacy badge from the readme
- Removes information relating to V2 DAS.

## Screenshots

N/A

## Steps to Test

Read the `README.md` file

2020-02-21 05:06 UTC, emilytrau requested changes

2020-02-21 05:06 UTC, angustrau commented on README.md
>  Imitates the Teensy serial connection by creating a virtual serial port. Note that this will only work on Unix systems - if you're running Windows, perhaps try running the script under [Windows Subsy
We could remove the teensy test scripts.

2020-03-06 02:47 UTC, emilytrau submitted a review, later dismissed
LGTM! We should remove the serial and Teensy test scripts from the Rapsi/Tests directory, but that can be another PR

2020-03-06 03:01 UTC, hallgchris submitted a review, later dismissed

2020-03-06 08:58 UTC, khanguslee commented
> LGTM! We should remove the serial and Teensy test scripts from the Rapsi/Tests directory, but that can be another PR

Thinking about creating a utils folder for our 'test' scripts

2020-03-13 01:19 UTC, emilytrau approved these changes

2020-03-16 04:35 UTC, hallgchris approved these changes

2020-04-19 13:00 UTC, khanguslee commented
It's funny because we pulled in https://github.com/monash-human-power/data-acquisition-system/pull/49 when this PR was already here. oops. Closing this PR.

2020-04-19 13:00 UTC, closed without merging