Blake haydon/add enums for mqtt
monash-human-power/MHP_DAS pull request #42
Opened 2020-02-26 11:20 UTC by Blake-Haydon

## Description

**Most important changes**
+ Converted topics into an enum file for easier readability and decreased hardcoding
+ Fix changed topics eg. /v3/wireless-module/<id>/low-battery. Now all of the code matches the spec on notion
+ Added new sensors (power, cadence and heartRate)
+ Added support for multiple mock sensors (any number can now be specified eg. 20)
+ Removed huge if statements to define the modules, now it is simply a function and you can specify what sensors you want in a list

**Less important changes** 
+ Fixed some documentation so now it makes sense
+ If statements now check the entire topic rather than just the start and the end
+ `if None` hack to specify all sensors has been removed so now all the sensors that are being mocked are just stored in an array
+ Saved file names are now generated by the logging script in the format `module_id + "_D%d-%m-%d_T%H-%M-%S" + ".csv"`

## Screenshots

<img width="365" alt="image" src="https://user-images.githubusercontent.com/23159604/75339846-672d5280-58e5-11ea-8f65-5ba723380f3e.png">
As many sensors as you need / want

## Steps to Test
1. Make sure mosquitto is running
2. Start logger `python3 mqtt_wireless_log.py`
3. Start mock modules `python3 mock_wireless_module.py -t 5 --id 1 2 3 4 5 666`

Watch as 6 fake modules generate and save data for 5 seconds

2020-02-26 11:32 UTC, emilytrau requested changes

2020-02-26 11:32 UTC, angustrau commented on Raspi/Test/DataToTempCSV.py
>          type = "DATA"
Message type could also be an enum

2020-02-26 11:32 UTC, angustrau commented on Raspi/Test/DataToTempCSV.py
> +        temp_filename = '.~temp_' + module_id_str + '_' + type + '.csv'
This could be an fstring

2020-02-26 11:32 UTC, angustrau commented on Raspi/Test/mock_wireless_module.py
> +            if module_id_num == 1:
If you declared the modules in a list or dictionary you wouldn't need this lookup anymore

2020-02-27 00:50 UTC, khanguslee reviewed
What an amazing Pull Request description. Really appreciate it. Pretty much got nothing else except for the already mentioned changes.

2020-02-27 09:37 UTC, hallgchris reviewed
Just one thing! Looks great

2020-02-27 09:37 UTC, hallgchris commented on Raspi/Test/enum_topics.py
> +        return '/v3/wireless-module/' + str(module_id) + '/battery'
Did you mean to reference `base` here rather than hardcode the string? Could also use an fstring.

2020-03-02 05:03 UTC, emilytrau submitted a review, later dismissed

2020-03-03 05:38 UTC, khanguslee approved these changes
LGTM. The filenames should not be generated by time as there is not RTC on the Bike DAS (for now). Can you generate filenames as per the old logger. Happy to have that as a new PR. But please make it a priority for now.

2020-03-05 05:08 UTC, hallgchris approved these changes

2020-03-05 05:21 UTC, emilytrau approved these changes

2020-03-05 06:31 UTC, merged